### ISSUE TITLE
Error 401 (Unauthorized) when doing GET request on my SData address

### ISSUE THREAD

**Issue by ratskin** [Sage/SData-2.0#111]
### I made a Stack Overflow post about this [here](https://stackoverflow.com/q/48646747/7304372).

I'm trying to integrate Sage 50 Accounts Professional V23 with my external application through SData. So far I've tried connecting, with the SData address I got through `Tools > Internet Options > SData Settings`, but when I make the GET request using the credentials I used to sign in to Sage 50, I get 401 unauthorized error.

Sage 50 is hosted on Windows Server 2012, I've tried using PowerShell to make the request and tried using the browser; both fail.

This is the PowerShell code I used:
```
$username = "MyUsername"
$password = ConvertTo-SecureString 'MyPassword' -AsPlainText -Force
$cred = new-object -typename System.Management.Automation.PSCredential -argumentlist $username, $password
Invoke-WebRequest -Credential $cred -Uri 'http://localhost:5493/sdata/accounts50/GCRM/{string-of-numbers-letters-and-dashes}/salesOrders'
```

When going to the same url through the browser, a browser window pops up asking for authentication. I provide it, then click login, after doing that the windows pops up again with empty username and password. No matter how many times I fill them out, I get the same thing. If I click "Cancel" instead of login, then I get a 401 unauthorized error

**Comment by darroncockram** [comment]
Just tried that and the problem looks to be that the Invoke-WebRequest command is not setting the authorization header despite the credentials being provided. The 401 response would be expected in this case.

I simply changed line 3 to this:
```PowerShell
$cred = new-object -typename 'System.Management.Automation.PSCredential' -argumentlist $username, $password

i.e. added quotes around the typename parameter as it is a string, and the authorization was correctly set following this and meant the request completed as expected.

**Comment by ratskin** [comment]
Thanks for the help @darroncockram.
Unfortunately this didn't solve it for me, though it may have been part of the problem. After making your change, I'm still getting this error:

```powershell
Invoke-WebRequest : The remote server returned an error: (401) Unauthorized.
At script.ps1:4 char:1
+ Invoke-WebRequest -Credential $cred -Uri 'http://localhost:5493/sdata/acco ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

**Comment by darroncockram** [comment]
The PowerShell code works OK for me so we can be confident it's that.

Given that you are unable to log in via a web browser and get a 401 response it would suggest that the credentials you re trying to use are not valid for that endpoint. Are you able to log in to the main Accounts application using the same credentials?

**Comment by ratskin** [comment]
Yes, I am able to login to the sage GUI with those credentials. I’m confirmed them multiple times.

It does ask for credentials when visited by the browser, that would suggest that the URL is correct. Can you confirm I have the right one?

**Comment by darroncockram** [comment]
If you can log on to the app but not to the endpoint it would suggest the endpoint is not connected to the same dataset as you are logging on to in the main application. Confirming this is not always simple as the main Accounts application uses physical paths but Sdata (quite deliberately) does not expose any physical path info which makes it hard to match them up.

Some things to check:
When you log on to the Accounts UI how many datasets do you have available to connect to?
Is the datapath for the dataset you are connecting to in the Accounts UI local or in a network location?
If you go to http://localhost:5493/sdata/$system/registry/*/endpoints?where=endPointType%20eq%20%27dataSet%27 and locate the one that matches the dataset identifier you are using in your URL does the dataset name match the company name that you are connecting to in the Accoutns UI?

**Comment by ratskin** [comment]
@darroncockram, thanks for the help. Unfortunately, I don't understand what a dataset is (in this context). Is a dataset each "module" on the left side of the UI, "Customers", "Quotations", etc.?
![screen shot 2018-02-08 at 12 42 54](https://user-images.githubusercontent.com/24547185/35972049-89a99c14-0cd0-11e8-8b6a-900d6251b0b6.png)

If that's true than here are my answers:

1. I can connect to all the datasets shown in the above image
2. I believe the dataset are local, though I'm unsure how to confirm this
3. Yes it does

**Comment by asterix187** [comment]
A dataset is a different trading company in Sage 50. Referenced by your '{string-of-numbers-letters-and-dashes}' section. Within each dataset will be a list of companies, products etc. 

Within the sData settings in Sage 50 the URL to the data should either be C:\ or \\localhost or \\servername etc. If its \\servername or a mapped drive like T:\ then the user running the sData service will need network access rights to the mapped/UNC folder path.

**Comment by ratskin** [comment]
@asterix187 thanks for that. I’ll check and get back to you. In the meantime I’d like to connect remotely. Would you mind explaining the process to me? I assume it’s pretty simple, but I’d love your input if you wouldn’t mind

**Comment by asterix187** [comment]
If you mean remotely over the internet or internal network all you will need to do is change the sData URL to be the remote name of the Sage 50 client you wish to use. For example if your local on a network but the Sage 50 client is on a machine called Sage50Client you could use:

http://sage50client:5493/sdata/accounts50/GCRM/-/salesOrders

If you wanted to use over the internet then you will need to use the external IP address of the network the client is on and then forward the external IP port 5493 to the internal IP and port.

So if your external fixed IP was 212.121.12.21 the URL would be:

http://212.121.12.21:5493/sdata/accounts50/GCRM/-/salesOrders

If you then created a public DNS record for the IP of sage50.mycompany.com you could use:

http://sage50.mycompany.com:5493/sdata/accounts50/GCRM/-/salesOrders

**Comment by darroncockram** [comment]
If you are planning on accessing Sdat over the Internet I would strongly recommend using HTTPS rather than the default HTTP.

1. There are no datasets shown in the  screenshot. When you first open Accounts you will see a screen titled select company. Each of the items in here (excluding the practice and demo data entries is a dataset).
2. The above screen shows the physical path that is used. If the path uses a mapped network drive or a UNC path then it is located on the network rather than locally. Datasets on mapped network drives will not be accessible via Sdata, and as @asterix187 metnions if the data is accessed via a UNC then the service user will need access to the location of the data files.
3. Localhost and the machine name can be used interchangeably but I would always recommend using the machine name for production code to ensure the context is always correct.

**Comment by ratskin** [comment]
Thanks both of you. The data path is local, it's not located on the network. See screen shot:
![screen shot 2018-02-08 at 22 45 58](https://user-images.githubusercontent.com/24547185/36000052-080449a0-0d22-11e8-9b69-45749b2dbe65.png)

**Comment by ratskin** [comment]
Hey @darroncockram @asterix187, just letting you know this issue hasn't been resolved. I'm still having trouble connecting. I'd appreciate any help you can offer.

**Comment by asterix187** [comment]
Have you tried giving 'everyone' access to the c:\programdata\sage\accounts\2017 folder. Not recommended for production but worth a test to see if its local folder permissions.

**Comment by ratskin** [comment]
Looks like it was already setup that way?
![screen shot 2018-02-13 at 15 52 34](https://user-images.githubusercontent.com/24547185/36155934-fdcebbf2-10d5-11e8-8e7b-ea6534ca7bf3.png)

**Comment by asterix187** [comment]
Ahh just one thing. Has the Sage 50 install been upgrade from an older version? Or was it a fresh install. We have found that upgrading to 2017 breaks sData feeds due to the way it which the installer doesn't register the new DLL's.

If its been upgraded from and earlier version I would suggest backing up the Company.000 folder (or copy>pasting it somewhere) then uninstalling and reinstalling the Sage 50 client.

**Comment by ratskin** [comment]
I've just made a fresh install of Sage50, on a separate instance of the windows machine. Still no luck
 😢. Any ideas?

**Comment by fonym** [comment]
@ratskin 
Did you every get this sorted?
This seems to be where all information on every forum and every question gets to.

**Comment by ratskin** [comment]
@fonym,
No such luck. My SO post only has 86 views and no answers in 5 months as well. I guess SData just isn’t very popular. For now I’m putting off setting this up, I might try again later. Maybe a fresh install will resolve it

**Comment by fonym** [comment]
@ratskin Thats a shame. Best of luck with it when you pick it back up.

**Comment by darroncockram** [comment]
> No such luck. My SO post only has 86 views and no answers in 5 months as well. I guess SData just isn’t very popular.

Sdata certainly isn't as popular as it was originally hoped to be. It has turned out to be fairly specialist subject with it really only applying to some Sage products with it really only gaining a small amount of traction with people interacting with Sage to Accounts (UK), so it's not a great surprise that this forum is largely the only place you'll find any info.

In terms of the original issue the PowerShell code works no problems for me. I've also not seen any problems connecting from a web browser. That's not me playing the 'works on my machine' card as I also have no issues even on a clean machine with a fresh install of Accounts and I've spoken with lots of other developers both inside and outside of Sage who can connect to the Sdata feeds without any problems.

I simply can't spot why it is not working for @ratskin. As the Sdata service is responding for the dateset there no reason I can think of that you would be unable to log on (provided the username and password are correct for the dataset being connected to of course).
