### ISSUE TITLE
Sage.Integration.Accounts50.SDOAdapter.SDOWorkspaceManager.GetCompany null key

### ISSUE THREAD

**Issue by ramblex** [Sage/SData-2.0#115]
After upgrading Sage accounts 50 we receive the following error when making an HTTP request to the following (or any other GCRM contract URL): `http://1.2.3.4:5493/sdata/accounts50/GCRM/-/$schema`

```
500 Internal Server Error
<?xml version="1.0" encoding="utf-8"?>
<diagnosis xmlns="http://schemas.sage.com/sdata/2008/1" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:sdatasync="http://schemas.sage.com/sdata/sync/2008/1" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:sdata="http://schemas.sage.com/sdata/2008/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmlns:sme="http://schemas.sage.com/sdata/sme/2007" xmlns:http="http://schemas.sage.com/sdata/http/2008/1">
  <sdata:severity>error</sdata:severity>
  <sdata:sdataCode>ApplicationDiagnosis</sdata:sdataCode>
  <sdata:applicationCode />
  <sdata:message>GET operation failed - Value cannot be null.
Parameter name: key

   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Sage.Integration.Accounts50.SDOAdapter.SDOWorkspaceManager.GetCompany(IRequest request)
   at Sage.Integration.Accounts50.SDOAdapter.SDOWorkspaceManager.GetWorkspace(IRequest request)
   at Sage.Integration.Accounts50.SDOAdapter.SDOWorkspaceScope..ctor(IRequest request)
   at Sage.Integration.Accounts50.SDOAdapter.SDORequestManager.CheckAccountsVariantSupport(String schema, IRequest request)
   at Sage.Integration.Accounts50.SDOAdapter.SDORequestManager.OnGetSchema(IRequest request)
   at Sage.Integration.Accounts50.SDOAdapter.SDORequestManager.GetRequest(IRequest request) (-1)</sdata:message>
  <sdata:stackTrace />
  <sdata:payloadPath />
</diagnosis>
```

Any ideas what might cause the error?

**Comment by asterix187** [comment]
What version of 50 were you on and gone to? Also do you use Sage Drive.

It appears that Sage have been very easy with sData in the past few revisions and has not done basic admin such as registering the correct DLL versions in the GAC on upgrades. It would be worth completely uninstalling the Sage 50 client and doing a fresh install of the latest version you are using.

We have also found some issues with sData in newer versions when using Sage Drive where it appears t hang randomly.

**Comment by darroncockram** [comment]
The error suggests there are no registered datasets that the Sdata service can access. Do you see any datasets listed if you query the endpoints: http://localhost:5493/sdata/$system/registry/*/endpoints?where=endPointType%20eq%20%27dataSet%27

**Comment by asterix187** [comment]
You will probably find that there are no listed endpoints in Sage 50 when going to the Tools etc option in Sage 50. In our experience recently, when an upgrade has been performed with the latest builds of Sage 50 the old sData files are left in the GAC and cause a conflict as the sData service gets the first ones it finds which are always the oldest ones.

**Comment by ramblex** [comment]
Thanks for the speedy responses. We've upgraded from 24.1 to 24.2.228.0 and as you suggest there's no dataSet endpoints:

```
<?xml version="1.0" encoding="utf-8"?>
<feed xmlns:atom="http://www.w3.org/2005/Atom" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cf="http://www.microsoft.com/schemas/rss/core/2005" xmlns="http://www.w3.org/2005/Atom" xmlns:sdatasync="http://schemas.sage.com/sdata/sync/2008/1" xmlns:sdata="http://schemas.sage.com/sdata/2008/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmlns:sme="http://schemas.sage.com/sdata/sme/2007" xmlns:http="http://schemas.sage.com/sdata/http/2008/1">
  <author />
  <category />
  <generator />
  <title>List of End Points</title>
</feed>
```

How would I go about removing the old sData files? Could I use `gacutil`?

**Comment by darroncockram** [comment]
The endpoint list you see in the Accounts UI is the same one you get from the endpoints query (Accounts actually issues that exact query to populate the list in the UI).

In terms of the assemblies in the GAC the versions there should be upgraded as part of the install of the install of the new version of Accounts. I've not seen these fail to be upgraded before. However even if they were not upgraded for some reason it should cause any major issues as the Accounts Sdata adapter is generally forwards and backwards compatible. Of course you'd be missing any bug fixes in the newer version so you definitely want to be on the latest version if possible. I'd if you are seeing problems with the Sdata adaper files not being upgraded I would recommend stopping the Sdata service before starting the Accounts installer and running the upgrade.

As to why you don't see any datasets following an upgrade this is likely due to the fact that installing a newer version of Accounts will change where the Sdata adapter searches to discover the datasets. If you open the Accounts UI - the latest version that was installed - and open a dataset from there it should subsequently appear in the list of available datasets in the endpoints query (subject to the location being accessible to the Sdata service of course).

**Comment by asterix187** [comment]
Registry: HKLM\SOFTWARE\Classes\Installer\Assemblies\Global
delete keys starting with Sage.Integration.Accounts50.SDO.Adapter
These keys prevent the dlls from being uninstalled by gacutil.

Copy gacutil (can get it from here if you dont have it https://www.dropbox.com/s/bi2ienk06n1rfz9/gacutil.exe?dl=0) to the Sage 50 dll folder (C:\Program Files (x86)\Sage\Assemblies\SData)

Run CMD as admin.

Move to the above folder (cd "C:\Program Files (x86)\Sage\Assemblies\SData")

Unregister the DLLs:
gacutil /u Sage.Integration.Accounts50.SDO.Adapter.GCRM.Feeds
gacutil /u Sage.Integration.Accounts50.SDO.Adapter

Reregister the DLLs:
gacutil /i Sage.Integration.Accounts50.SDO.Adapter.GCRM.Feeds.dll
gacutil /i Sage.Integration.Accounts50.SDO.Adapter.dll

Start the Sage sdata service.

**Comment by asterix187** [comment]
Darron, just to note from 24.1 we have noticed almost every single install has this issue with sData. From analysis its pretty clear that the DLL's are not updated when going to 24.1 or 24.2 like they used to be.

**Comment by darroncockram** [comment]
I'm not 100% sure what changes if any went in to the Sdata adapter in 24.2. I'll check with the Accounts team and see if there is anything that might be causing problems.

**Comment by asterix187** [comment]
Hi Darron, thanks.

**Comment by ramblex** [comment]
Thanks for the suggestions on re-registering the DLLs. We've run the commands successfully but we're still seeing the same error message. Could there be anything else causing the problem? Is there any other output which would help?

**Comment by darroncockram** [comment]
Are you able to open any datasets in the new version of the Accounts UI that you have installed? If so are the path(s) to the data local or on the network?

**Comment by ramblex** [comment]
We can open and access our data through the UI as normal. We're using a network drive to store the data. Could the problem be related to this?: https://github.com/Sage/SData-2.0/issues/43

**Comment by asterix187** [comment]
The sData service needs to run under a user account that have access to the data on the network drive. By default it runs under Local System which will not have access. If you edit the sData service Log On As settings and set to a network user who has access you should see the sData endpoints should up in Sage 50 under the Tools>InternetOptions>SData Settings section.

Was the data always on the network share, even pre upgrade?

**Comment by ramblex** [comment]
We're now running the service as an administrator who access to the directory the data is stored in but we're still not seeing the endpoints.

The data has been in the same location for the past few upgrades.

Is there any way to run SData from the command line or any logs files which might contain error messages?

**Comment by asterix187** [comment]
You can browse the URL of sData and use curl to query but you won't get any meaningful response because there won't be any datasets to access.

Are there are brand new Sage 50 clients installs that were not upgraded but cleanly installed? If not have you tried uninstalling and reinstalling or is it possible to install a the new client on a non sage 50 computer just as a test.

**Comment by darroncockram** [comment]
> We're now running the service as an administrator who access to the directory the data is stored in but we're still not seeing the endpoints.

When you mentioned you were using a network path is it a mapped drive or a UNC path? It will need to be the latter for it to be accessible to the Sdata service.

> Is there any way to run SData from the command line or any logs files which might contain error messages?

Afraid not. It is implemented as a Windows service and can't be run interactively. You could issue requests to it from the command line e.g. using curl, but that's not going to help to diagnose the problem here. If the service does encounter any errors there will be written to the Windows application event log so you can check there to see if there if it had any problems.

**Comment by fonym** [comment]
Hi @ramblex,
It's great that you managed to get your problem resolved - I'm struggling with the same thing and as you'll know, there is very little information around about Sage50 use of sData.
Could you tell me if those file locations you mention above were on the data server or client PC?

Thanks in advance

**Comment by ramblex** [comment]
Hi @fonym, I was running the Sage client on the same PC where the data drive had been mounted.

**Comment by fonym** [comment]
Thanks @ramblex, that wasn't my issue then so I will keep looking.
Thanks again.
