### ISSUE TITLE
Sage50 Accounts V24 - Sdata - GET operation failed

### ISSUE THREAD

**Issue by fonym** [Sage/SData-2.0#117]
Hello,

I am trying to view my Sage 50 (v24) account data using sdata and a web browser but am getting the following error back;

http://localhost:5493/sdata/accounts50/GCRM/-/tradingaccounts

GET operation failed - Value cannot be null. Parameter name: key at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument) at System.Collections.Generic.Dictionary`2.FindEntry(TKey key) at System.Collections.Generic.Dictionary`2.get_Item(TKey key) at Sage.Integration.Accounts50.SDOAdapter.SDOWorkspaceManager.GetCompany(IRequest request) at Sage.Integration.Accounts50.SDOAdapter.SDOWorkspaceManager.GetWorkspace(IRequest request) at Sage.Integration.Accounts50.SDOAdapter.SDOWorkspaceScope..ctor(IRequest request) at Sage.Integration.Accounts50.SDOAdapter.Feeds.Company.GetActiveCompany() at Sage.Integration.Accounts50.SDOAdapter.Feeds.tradingAccountFeed..ctor() at RuntimeRequestHandler21e5a4ed06344778ba614397cb993375.CreateFeedInstance() at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.CreateFeedInstance() at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.OnGetRequest(IRequest request) at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.GetRequest(IRequest request) at Sage.Integration.Accounts50.SDOAdapter.SDORequestManager.OnGetResource(IRequest request) at Sage.Integration.Accounts50.SDOAdapter.SDORequestManager.GetRequest(IRequest request) (-1)

When I use the link
http://localhost:5493/sdata/$system/registry/*/endpoints?where=endPointType%20eq%20%27dataSet%27
I don't get any datasets listed but I can also not see any datasets when looking at the sdata parameters inside the Sage 50 Accounts client, even though my accounts data is referenced using UNC and my sdata service is using a domain account that has access to the the account data.

I have tried un-registering and re-registering the Sage.Integration.Accounts50.SDO.Adapter dll's that I saw mentioned on a different post but that has not helped.

What am I missing?

**Comment by fonym** [comment]
@asterix187 

Thanks for getting back to me so quickly.
My Sage 50 client is on a different server to the account data but no I can not see any companies when I go to Tools>Internet Options>SData Settings then click the Details button.

The client was a fresh install.

**Comment by asterix187** [comment]
Great, so if you go to the services on the server (Start>services.msc) and find the Sage SData Service. Edit the properties and go to the Log On tab. Set the 'This Account' option to a user account that has rights to read/write to the shared folder you have on the network. Its also worth setting the data path in the Sage 50 client to a UNC path rather than a mapped drive. Such as:

\\server\sage\accdata

rather than

Z:\accdata

This issue is that the SData provider does not have rights to access the Sage Data Path folder and is therefore not returning any datasets.

**Comment by fonym** [comment]
I did notice that solution a lot when searching the internet so have already set the sdata service to log on with a domain user that has access to the account data.

I also believe my data path is already UNC (it is UNC inside the COMPANY file) but I don't know where to see or change it inside the Sage 50 account client.

**Comment by fonym** [comment]
I am still struggling with this. Are there any other suggestions I could try?

**Comment by fonym** [comment]
@darroncockram Are you able to help me?

**Comment by darroncockram** [comment]
Sorry for the delay in responding. @asterix187 is correct in that the problem is you are accessing data over the network. The original error you are getting is because you have no datasets that the Sdata service can access and you are requesting a dataset (the default dataset) that does not exist.

What you see in the Accounts UI under Tools>Internet Options>SData Settings is the exact same thing you will see from the registry request. In fact the Accounts UI is issuing that exact same request to determine what is available via Sdata.

The suggested fix from @asterix187 is correct but only part of the solution which may be why you are still having issues. Sdata runs as a service and therefore mapped network drives simply do not exist (mapped drives in Windows require a user session). If you want the service to access data on the network you must use UNC paths instead of mapped drives.

The second gotcha, and the reason you will still be having issues is that the Sdata service needs permissions to access the UNC path in which the data is held. The service actually runs under the LocalSystem account by default and this account has no network access (and cannot have network access in fact). You will need to change the account that the service runs as to one that has network access and permissions (read and write) to the UNC path of the data. Once you do that and restart the service the dataset should be available, show up in the registry query, and be queryable in your browser.

Hope that helps

**Comment by darroncockram** [comment]
P.S. As a good practice thing I would strongly recommend that you do not use the default dataset identifier (the dash) to reference your data. Always use the Guid identifier instead which you will see in the response to the registry request.

The reason for this is that (for technical and fairly dull reasons) the actual data that the default dataset maps to can actually change. The Guids on the other hand never change as they are stored with the data itself.

**Comment by fonym** [comment]
Thanks @darroncockram and @asterix187. I think I have done all of that and am still having problems.
Perhaps if I show you in screen shots you can point out what I'm missing.

Here you can see that the data directory is a UNC path.
![image](https://user-images.githubusercontent.com/19993499/43631089-210913ec-96fa-11e8-84eb-d2c7a6036e67.png)

Here you can see the sdata service on the data server is set to log on with the domain administrator. The same is true for the sdata service running on the client server but I don't think we use that one do we.
![image](https://user-images.githubusercontent.com/19993499/43631015-e136b18e-96f9-11e8-87c3-685d47dba542.png)

Here you can see the domain administrator has full control over the UNC path of the data directory
![image](https://user-images.githubusercontent.com/19993499/43631213-75944760-96fa-11e8-9f01-9344719f08d1.png)

But yet still no datasets are showing in Sage accounts
![image](https://user-images.githubusercontent.com/19993499/43631236-8ab81842-96fa-11e8-9c6e-dfadb504fae6.png)

I clearly don't understand something but you don't know what you don't know right?

**Comment by darroncockram** [comment]
Have you changed the user that the Sdata service is running as to one that has network access to the share? Also you'll want to confirm the NTFS permissions on the data location.

**Comment by fonym** [comment]
Hi Darron, I think images 2 and 3 show that.

**Comment by darroncockram** [comment]
Image 3 show share permissions rather than NTFS permissions

> Here you can see the sdata service on the data server is set to log on with the domain administrator. The same is true for the sdata service running on the client server but I don't think we use that one do we.

Sorry I missed that comment first time around. Can you clarify what you mean by the 'client server' here? The only service that you need to worry about is the one on the machine you are issuing the Sdata requests to. That will need to be running as a user with access to the UNC location of the data and permissions to the data.

**Comment by fonym** [comment]
Thanks Darron,

As you can see, the domain administrator also has NTFS permissions
![image](https://user-images.githubusercontent.com/19993499/43647987-1593d4ac-9731-11e8-9ba9-103cbe4b765e.png)


The server, on which the Sage 50 accounts client application runs, also has an sdata service running, which is also run using the  domain administrator account.

**Comment by fonym** [comment]
So to clarify.
There are two servers, the data server (192.168.0.1) and the client server (192.168.0.2)
I have been querying sdata using both IP's, because I can't get it working, no matter what I do, but I had assumed I was supposed to be querying sdata using the data server IP.

Is that correct?

Interestingly though, having just stopped the sdata service on the client server and checked the sdata settings on the client, I get the below screen showing the client application is using the sdata service on it's local host.

![image](https://user-images.githubusercontent.com/19993499/43648802-56d596ec-9733-11e8-8f5f-f3573f0b2e41.png)

Which I guess makes sense but it does raise the question as to what the sdata service on the data server is for.

**Comment by darroncockram** [comment]
Hmmm. That sounds like it should work. Do you have other versions of Accounts installed on the client PC? 

You could try creating a dataset locally on the client PC and see if that is showing as available via Sdata.

**Comment by darroncockram** [comment]
> So to clarify.
There are two servers, the data server (192.168.0.1) and the client server (192.168.0.2)
I have been querying sdata using both IP's, because I can't get it working, no matter what I do, but I had assumed I was supposed to be querying sdata using the data server IP.

Either should be able to work. Generally speaking it is better if the data is local to the Sdata service instance as it's better from a performance point of view (and typically simpler too).

> Which I guess makes sense but it does raise the question as to what the sdata service on the data server is for.

The Sdata service is installed anywhere the Accounts application is installed to. As noted above you can technically use either to access the Sdata feeds but it's generally preferable to access is via the machine that hosts the data.

**Comment by fonym** [comment]
I don't have any other versions of Accounts installed but it isn't the first version of accounts that we've had so there are old services which have been disabled. By Sage technical while they were upgrading it.

What you say about the services makes sense but it does mean all sdata services will need UNC path access doesn't it? Both mine have, I just wanted to clarify.

I have now created a new company and stored the data locally on the client machine (although DEMO and PRACTICE already existed) and there are still no datasets showing.

**Comment by darroncockram** [comment]
> What you say about the services makes sense but it does mean all sdata services will need UNC path access doesn't it? Both mine have, I just wanted to clarify.

Not at all. If the data is local then you can (and as noted above preferably should) us a local data path.

> I have now created a new company and stored the data locally on the client machine (although DEMO and PRACTICE already existed) and there are still no datasets showing.

Demo and practice data are not shown as datasets in Sdata as they have special handling in the Accounts application. Only 'user datasets' are made available via the Sdata feeds.

It's interesting that a local dataset does not show. Is the Accounts 50 application showing as available in the response to a registry request?

**Comment by asterix187** [comment]
Just to add, you can use the demo data set as a live company by adding the dataset to the as a 'New Company' and just pointing the company to the demo data ACCDATA folder. As Darron has said, both of those datasets, whilst selectable on starting Sage 50, are not shown via sData by default.

**Comment by fonym** [comment]
Thank you both for your help so far.

When you say @darroncockram "registry request" I don't fully know what you mean but when I navigate to http://apps-02:5493/sdata/$system/registry I get the response "Unable to locate a handler to process the request '$system/registry'".

And when I navigate to http://apps-02:5493/sdata/$system/registry/*/endpoints I get the below screen which shows the Accounts 50 app (I think)

![image](https://user-images.githubusercontent.com/19993499/43702288-34a0275c-9951-11e8-90d0-4086da17447d.png)

**Comment by darroncockram** [comment]
Sorry by a registry request I meant the endpoints request you have made. That does show the application as being registered but no datasets available.
I would recommend creating a dataset locally and seeing if it is then available in the endpoints response.

**Comment by fonym** [comment]
Hi Darron,

I have a local dataset that I have called TestCompany (original I know)

![image](https://user-images.githubusercontent.com/19993499/43840479-b67b8c8a-9b18-11e8-9d44-96b8514fb3ed.png)

![image](https://user-images.githubusercontent.com/19993499/43840457-a9f54eba-9b18-11e8-9191-b9810577cd6b.png)

But there is still nothing showing in Sdata details

![image](https://user-images.githubusercontent.com/19993499/43840538-d5497640-9b18-11e8-8338-327f81905b4f.png)

OR when I make an enpoint request.

![image](https://user-images.githubusercontent.com/19993499/43840566-e647977e-9b18-11e8-8c0f-d2d3241ecfea.png)

**Comment by darroncockram** [comment]
OK, that takes all the networking out of the equation so it does not appear to be that.

I see you said that you have had version of Accounts installed previously but Technical support made some changes when installing the upgrade. It's possible that something here is not quite right. If you open up regedit.exe (usual warnings apply) and navigate to 
 HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Sage\Line 50\SettingsFolder what path is held in this setting, does that path exist and does the user that the Sdata service is running as have access to that path?

**Comment by asterix187** [comment]
@fonym I can't remember whether you said this was an upgraded client or not. If it was try the below (courtesy of a colleague):

Stop the Sage sdata service

Registry: HKLM\SOFTWARE\Classes\Installer\Assemblies\Global
delete keys starting with Sage.Integration.Accounts50.SDO.Adapter
These keys prevent the dlls from being uninstalled by gacutil.

Copy gacutil (https://www.dropbox.com/s/bi2ienk06n1rfz9/gacutil.exe?dl=0) to the Sage 50 dll folder (C:\Program Files (x86)\Sage\Assemblies\SData)

Run CMD as admin.

Move to the above folder (cd "C:\Program Files (x86)\Sage\Assemblies\SData")

Unregister the DLLs:
gacutil /u Sage.Integration.Accounts50.SDO.Adapter.GCRM.Feeds
gacutil /u Sage.Integration.Accounts50.SDO.Adapter

Reregister the DLLs:
gacutil /i Sage.Integration.Accounts50.SDO.Adapter.GCRM.Feeds.dll
gacutil /i Sage.Integration.Accounts50.SDO.Adapter.dll

Start the Sage sdata service.

**Comment by fonym** [comment]
Thanks @asterix187,

I saw you suggested that on another post when I was originally looking for solutions and have alread tried. No luck I'm afraid.

**Comment by asterix187** [comment]
No worries. Its a bit odd.

**Comment by fonym** [comment]
Its very frustrating too.

**Comment by asterix187** [comment]
If you do a fresh Sage 50 install on another pc does it then have sdata datasets shown?

When testing I always add the demo data in as a proper company by using Add Company> and selecting the demo data ACCDATA folder.

**Comment by darroncockram** [comment]
Running gacutil against the assemblies would really only make a difference if the Sage 50 Accounts application is not listed in the response to the registry request. The problem is definitely related to discovering or loading the datasets. Definitely worth trying a clean install with the demo data as per @asterix187 suggestion.

**Comment by fonym** [comment]
Ok,
I installed sage 50 accounts on my local PC and added the Demo data as a company and WAS able to see this using sdata.
I then added the real company data, changed the sdata service logon account and WAS able to see that in sdata too.

So I spent the afternoon uninstalling sage 50 accounts v24 from the client server (there were numerous references to v22 services too which I needed the help of support to remove).
When the server looked clean, I installed sage 50 accounts and added the Demo data as a company but alas could NOT see it in sdata.
I also added the real company, changed the sdata service logon account and can still NOT see that data in sdata.

So it looks to be server related but I simply don't know what it could be.
