### ISSUE TITLE
sage sdata url with UUID not working

### ISSUE THREAD

**Issue by hemaljadav** [Sage/SData-2.0#118]
HI

I have got sage 23 with all the updates and service pack for two companies. Initially had problem with URL which generated wron -1 at the end but now it different UUID,

So when i type the url in browser http://myPC:5493/sdata/accounts50/GCRM/-/tradingaccounts" it opens the first company data but if it type http://myPC:5493/sdata/accounts50/GCRM/{C4C463BE-B098-4A7D-A23B-D1A92B8DCB59}/tradingaccounts it just ask for username and password then it does not got any further.
No errors are thrown either.

Any suggestion or advise?

Best regards
Hemal

**Comment by asterix187** [comment]
Is the dataset id for the same company or is that for the second dataset? If so try stopping sData and then trying the second URL straight away.

**Comment by darroncockram** [comment]
The fact that you are being prompted for a username/password would suggest that the dataset Id you are specifying is valid. What happens if you enter valid credentials with access to that dataset?

**Comment by asterix187** [comment]
Just to add to my question. We have found that because SData hod open the connection for up to a few minutes after a request is made, when switching datasets the data can actually be returned with a different dataset of data even when you specify another dataset GUID. The only way we have found to quickly release the old dataset connection is stop and start the SData service and make a fresh connection to the required dataset.
