### ISSUE TITLE
Could not load file or assembly 'Sage.Common.LinqBridge'

### ISSUE THREAD

**Issue by mbharanidharan88** [Sage/SData-2.0#138]
I am trying to fetch the tradingAccounts through the SDATA URI with the static ip address after port forwarding and getting the below error. Any Ideas please?

> Could not load file or assembly 'Sage.Common.LinqBridge, Version=1.0.0.0, Culture=neutral, PublicKeyToken=c59b718b5ca510a8' or one of its dependencies. The system cannot find the file specified.

**Comment by darroncockram** [comment]
That file should be installed in the GAC

**Comment by mbharanidharan88** [comment]
ya it is, but I have created the API which will be hosted in cloud and there it doesn't have Sage application installed. 

Please refer this #139

**Comment by darroncockram** [comment]
If there is no Sage application installed then the SIF will not have been deployed. You'll either need to install a Sage application or install the SIF separately for the assemblies to be available.

**Comment by mbharanidharan88** [comment]
> If there is no Sage application installed then the SIF will not have been deployed. You'll either need to install a Sage application or install the SIF separately for the assemblies to be available.

Ya, I am just referring the below assemblies and it works without Sage Installation.

- Sage.Common.Syndication
- Sage.Integration.Client
- Sage.Integration.Server.Model
- Sage.Utilities

**Comment by darroncockram** [comment]
If you are just re-distributing those 4 assemblies you are definitely missing some dependencies. I'd be a little surprised that an application could run if only those assemblies are distributed as I would have expected the assembly binding to fail due to missing dependencies (as per your original error), If the app is working then it will be more through luck than design and I would anticipate problems with certain code paths or as you add features to the application.

If you do not wish to install an application such as Sage 50 Accounts then you should be distributing the SIF using its standalone installer. These are the only supported methods of deploying the SIF and will guarantee that all dependent assemblies are deployed to a target machine.

**Comment by mbharanidharan88** [comment]
Ahh Ok!. I thought those 4 assemblies would suffice. Visual 2012 plugin for "Add sdata reference" just adding those 4 libraries as reference and so I just copied those to the Visual 2017 Project.

Also, I am using **tradingAccounts** and **salesInvoices** and I am not facing any issue yet.

**Comment by darroncockram** [comment]
Those assemblies have dependencies themselves. As I say I'm a bit surprised if the application is running without the full set of dependencies. If it is running without them I'd guess that would be the .NET framework will be loading them just in time. So whilst it may work at the moment it is very possible that you will encounter issues as you add functionality and exercise code paths that you aren't currently.

Off the top of my head you would also need Sage.Integration.Diagnostics.dll, Sage.Integration.Server.Model.dll and antlr.runtime.dll. Note that is not necessarily an exhaustive list as deploying he loose files is not something that has been tested. It may work and you may get away with it but it is not an officially supported scenario so your mileage may vary.

**Comment by mbharanidharan88** [comment]
>  as you add functionality and exercise code paths

Yes, I think after your comments but for now, with the functionalities, I've integrated it is working fine. However, as you suggested I will install the SIF in every individual machine.

Thank you!
