### ISSUE TITLE
SDATA customer UUID frequently has changed 

### ISSUE THREAD

**Issue by letoncse** [Sage/SData-2.0#163]
Dear All,
I'm keeping Customer UUID in my application and with querying with this UUID. I saw UUID is changing frequently in SDATA for same customer. you know why its happening ?
![image](https://user-images.githubusercontent.com/1812631/100863051-e4e14880-348b-11eb-9b80-3da290b2b68d.png)
Example: for same customer UUID in Sdata
previous UUID: 44818811-15b1-4703-96e7-f788c063f2dc

New UUID: 9066f8ac-9f3a-461f-b302-0b942884ad56

@darroncockram , your attention please. Thanks !

**Comment by darroncockram** [comment]
Are you seeing this across all datasets or just a specific one?

If no UUID has been set for a record yet (i.e. never been accessed via Sdata previously) then a new one is generated and then stored with the data so it is there and returned for any subsequent calls. Can't think of a good reason for the UUIDs to change between calls unless something is interfering with the storage of the UUIDs but that is not something I've ever come across so would be good to know if it is isolated to a dataset or not?

**Comment by letoncse** [comment]
> Are you seeing this across all datasets or just a specific one?
-- Its not happening for all customers. Sometimes it happening for some customers.   

> If no UUID has been set for a record yet (i.e. never been accessed via Sdata previously) then a new one is generated and then stored with the data so it is there and returned for any subsequent calls. Can't think of a good reason for the UUIDs to change between calls unless something is interfering with the storage of the UUIDs but that is not something I've ever come across so would be good to know if it is isolated to a dataset or not?

--I'm using UUID to transfer invoice, credit memo purpose. like 2 months ago invoice transfer successfully but now its not transferring cause of UUID changed. I cant figure out why its changing. its a isolated case. Thanks

**Comment by darroncockram** [comment]
> I'm using UUID to transfer invoice, credit memo purpose. like 2 months ago invoice transfer successfully but now its not transferring cause of UUID changed. I cant figure out why its changing. its a isolated case. Thanks

Is it consistently the same (new) UUID now or is it a different one each time you retrieve it via Sdata?

If it is consistently the same now but different to an earlier one then one thing that could cause that is if an invoice was entered and you processed it, then later on the data was restored and the invoice was re-entered. Technically that would make it a different record even if the details entered were exactly the same as previously. Also the same thing could happen even if the invoice exists but has not been accessed via Sdata, you then process it via Sdata, then restore a backup and access it via Sdata again. This is due to the aforementioned just-in-time generation of the UUIDs.

If it is different every time then that would suggest something has gone wrong with the storage file for the UUIDs so you'd be in a data repair situation then.
