### ISSUE TITLE
Price list Name displays the Description

### ISSUE THREAD

**Issue by asterix187** [Sage/SData-2.0#42]
Hi, 

When querying the pricelists in Sage 50 sData both the name and description display the description text, i.e. name = 'TESTPL' Desc = 'Test Price List' returns 'Test Price' List for both fields.

However, in the tradingaccountsummary record the pricelist is stored as the name value ('TESTPL') so there is no way to reference the price list for the account. 

Is there any other way of referencing the price list from the Trading Account Summary?

Thanks

**Comment by asterix187** [comment]
Ok answered my own question. If you include the priceLists in the standard tradingAccount you can get the linked pricelist. I still think there is a bug where the priceLists NAME field should show the name not the description.

**Comment by darroncockram** [comment]
As you've already found including the prices list on the tradingAccount would be the right way to go.

The field names and data in may not match up exactly with those in the Sdata feeds as the Sdata implementation is based on the GCM contract, which is generic to fit any sage product rather than being Accounts 50 specific. This means that sometimes, as in this case, there is not a simple 1-to-1 mapping of data. As it happens the Accounts UI is actually what is incorrect/confusing. What is shown in the Accounts 50 price list UI as 'Name' is really the price list reference, and what is displayed as 'Description' is really the name of the price list. Possibly because of this UI strangeness, when implementing the Sdata feeds the Accounts team have chosen to include what is actually the price list name in both the name and description properties.

Hope that helps.

**Comment by asterix187** [comment]
Hi, thanks for the comments back. All makes sense to a point but the fact that in sData both the Name and Description returns the same value is a bit annoying. We have resolved by creating a helper method to return the price list for the tradingAccount based on an applicationID and then we adjust the serialised json before we post to the other sData 2.0 provider we are interfacing with.
