### ISSUE TITLE
Sage 50 Accounts SData Details Not Showing Companies

### ISSUE THREAD

**Issue by geoffo** [Sage/SData-2.0#43]
Can you please explain how the Sage 50 Accounts SData Details page (Tools -> Internet Options -> SData Settings -> Details) is populated with Companies?  Currently there is a case where we aren't seeing any companies listed.  Does it look within a specific directory or some file?  Any help and information that can be provided would be much appreciated.

**Comment by asterix187** [comment]
Hi, in our experience the main reason why companies are not shown in sData is due to permissions on the Sage 50 folder location. Based on your question I assume the data does not reside on the machine you are using the client on. Things like mapped drives cause a particular difficulty and so generally its best to use UNC paths to the folder on the client machine you are using as your sData provider. Another solution is to set the sData Service logon rights to a user who has full rights over the network share/map drive. A quick test we use is to backup the company data, put it on the local client machine then add it to the client via 'Add Company'. Once added to the client you should see the data in the sData settings.

**Comment by darroncockram** [comment]
asterix187 is spot on with the advice there. Just to flesh this out a bit:

The Sdata service uses the same company list as the Accounts application does so if it's showing in the app but not in the Sdata feeds it must be an issue accessing the data path for the company.

Mapped drives don't work as they are only available when logged on interactively but Sdata is running as a service so if you are accessing data over a a network you'd need to convert these paths to UNCs.

On the permission front the service runs as LocalSystem by default so this would definitely need to be changes to a user with access to the network location(s) of the data as LocalSystem does not even have access to the network stack.

Having said that I would advise that from a performance point of view it would be better for the Sdata service be run on the same device that holds the data and to access the data via local path if possible. Having the service access the data over the network can certainly work (taking the above advice in to account), it's just that it's a little slower than accessing data held locally. How much slower obviously depends on a number of factors so your mileage may vary.

**Comment by geoffo** [comment]
Thanks for your help asterix187 and Darron.  This was the issue.

**Comment by vibs2006** [comment]
As per latest updates if you select "Use Existing Company from your network" then even changing the credentials might be not required for SData
![image](https://user-images.githubusercontent.com/18658498/65869302-d125e800-e397-11e9-992b-7f155c9eb61e.png)
