### ISSUE TITLE
Unable to create tradingaccount with currency and reference number.

### ISSUE THREAD

**Issue by PraneethKP** [Sage/SData-2.0#76]
I can set both but not setting up in sage. What may be the reason? Is there any property we need to set for this?

**Comment by darroncockram** [comment]
You don't say which Sdata adapter this relates to but I'd guess you are using Sage 50 Accounts as both the reference and currency are automatically generated for the tradingAccount type in that implementation. There is currently no way to set them via the Sdata feeds I'm afraid.

**Comment by PraneethKP** [comment]
Thanks darroncockram,
                       In which manner SIF is choosing the default currency.By setting that is there any possibility as tweak to resolve the issue?

**Comment by darroncockram** [comment]
The SIF does not set the default currency the adapter (Sage 50 Accounts in this case) sets it. The adapter uses the base currency of the target dataset to set the default currency for any new tradingAccount.

**Comment by PraneethKP** [comment]
Please could you provide me the list of attributes supported by SIF for creating/Updating Trading Accounts.
Also is there any option available for me to find out the list of attributes without bothering you too much.
Thanks in advance.

**Comment by darroncockram** [comment]
Sdata uses a self documenting system via $schema endpoints.  Please see this page for information on metadata queries: http://sage.github.io/SData-2.0/pages/core/0400/.

**Comment by binish007** [comment]
Hi guys, I have a question here.. Hope you would be able to help.
From the above thread I understand we cannot create/update the default currency using SIF. 
We are trying to integrate our Ecommerce site with Sage, but the issue is some of the invoices for the customers are created in USD, EUR etc.. So if I had to push an invoice from the Ecommerce application to Sage, can it bring the source currency as well? Even the customers default currency is set to GBP please.

**Comment by darroncockram** [comment]
> From the above thread I understand we cannot create/update the default currency using SIF.

The SIF is not the issue. It is the specific adapter, the Sage 50 Accounts one in this case, that unfortunately does not support setting the currency on a tradingAccount.

> We are trying to integrate our Ecommerce site with Sage, but the issue is some of the invoices for the customers are created in USD, EUR etc.. So if I had to push an invoice from the Ecommerce application to Sage, can it bring the source currency as well? Even the customers default currency is set to GBP please.

In Sage 50 Accounts the invoice inherits the currency from the customer (tradingAccount) so I'm afraid you would only be able to generate an invoice for the base currency as you can only create tradingAccounts in base currency. For more sophisticated integrations such as multi currency support you'd need to use SDO - the Sage 50 Accounts specific SDK.

Somewhat off topic for this forum but just for info - you can only create non-base currency customers and invoices in Sage 50 Accounts if you have the foreign trader module enabled in any event so any integration will need to factor this in to avoid generating errors.

**Comment by asterix187** [comment]
It is actually possible to set the currency of an invoice to be a different currency than the trading account in Sage 50.  However its probably best to have a trading account per currency for none account web orders i.e. a GBP Web Sales, EUR Web Sales etc.  Otherwise you will experience standard financial issues with exchange rates and tax. 

If you set the currency field of the invoice to the text of the currency, i.e. GBP, EUR, USD it will set the currency accordingly. It posts the currency as per the value so if you post 100 as EUR to a GBP trading account it will use the sage 50 currency conversion values and show the value in EUR and GBP.

**Comment by darroncockram** [comment]
> If you set the currency field of the invoice to the text of the currency, i.e. GBP, EUR, USD it will set the currency accordingly. It posts the currency as per the value so if you post 100 as EUR to a GBP trading account it will use the sage 50 currency conversion values and show the value in EUR and GBP.

You could set it when using SDO but not via the Sage 50 Accounts Sdata adatper I'm afraid. There is simply no mapping of the currency property for the salesInvoice. If you set it to something, even a valid currency code, it will simply be ignored, the invoice will be created as a base currency invoice and you will see in the return data from the POST that the currency as the base one rather than the one you set in the request.

**Comment by binish007** [comment]
Thanks Guys.. Excellent support from all the quarters :-)

asterix187, I have adapted your suggestion and by creating different customer (AA0USD, AA0EUR, AD0GBP) in Sage seems resolved the issue.  👍 👍 👍  Thank you..

Darron, much appreciate your support.. It really helped us to the reach the goal.. 👍 👍 👍
