### ISSUE TITLE
Sage 100 Compatibility

### ISSUE THREAD

**Issue by mitchwoloschek** [Sage/SData-2.0#77]
Just installed the Native SData Provider Adapter for my instance of Sage 100 ERP 2017 and I was wondering if SData 1.1 is compatible with Sage 100 or not. When trying to access anything other than the MasContract from the MasApp on my web service I get a not found error. Any clarification would greatly be appreciated.

**Comment by mitchwoloschek** [comment]
I guess I'm also wondering is if I have to generate my own contracts/schemas i.e GCRM, etc. and add them to my web service hosting the SData Provider Adapter.

**Comment by darroncockram** [comment]
>  I was wondering if SData 1.1 is compatible with Sage 100 or not.

I'm not as familiar with the Sage 100 implementation but yes, I believe it should be compatible with the Sdat 1.1 standard.

> When trying to access anything other than the MasContract from the MasApp on my web service I get a not found error.

They are the only contracts that it supports so that would be expected.

> I guess I'm also wondering is if I have to generate my own contracts/schemas i.e GCRM, etc. and add them to my web service hosting the SData Provider Adapter.

You cannot add a schema to a provider. The provider itself must implement a contract. It's a bit of a more advanced topic but you can create your own Sdata provider and implement support for any contract you like. I created a short series of videos a while back on this if you are interested - www.youtube.com/playlist?list=PLF77156B5D2FD4BA4.

**Comment by mitchwoloschek** [comment]
From a pure integration standpoint, do you think it would be better to use BOI or SData when trying to integrate with Sage 100?

**Comment by darroncockram** [comment]
That would very much be an 'it depends'. If you are creating a tightly coupled or high throughput integration BOI would likely be the better option. If you are creating something more lightweight then Sdata may be suitable.. Sdata integrations are often easier and certainly more generic however generally speaking the Sdata providers are not as fully featured as the product specific SDKs so it's worth checking if the Sdata provider/contract you are considering offers all the features you will require.

**Comment by mitchwoloschek** [comment]
I'm just trying to create an integration service that is bi-directional and can perform CRUD operations on a few objects/tables. Sdata definitely seems like the one that is easier to use, I'm just having trouble with the whole Sdata provider/contract part. I'm going through those youtube videos you mentioned and I'm not sure where the url in the beginning of "SData Providers 1 - Start writing an SData provider using the SIF"  is coming from.

**Comment by mitchwoloschek** [comment]
Ahh I now see why you have to create your own SData Provider/contract because the Mas90Contract from the Native SData Provider Adapter is ReadOnly...

**Comment by darroncockram** [comment]
> I'm going through those youtube videos you mentioned and I'm not sure where the url in the beginning of "SData Providers 1 - Start writing an SData provider using the SIF" is coming from.

Not sure which URL you are referring to. The endpoints one I show at the beginning of the video? If so that is just one of the 'well known' endpoints covered by the Sdata specification. The one I show in the demo is served up from the SIF.

> Ahh I now see why you have to create your own SData Provider/contract because the Mas90Contract from the Native SData Provider Adapter is ReadOnly...

Not all providers are read only but yes, the Mas90 one is I believe. If you are looking at having to write back to Sage 100 I suspect that BOI is going to be simpler choice for you. You certainly could still create your own Sdata provider and contract but the provider would have to be built on something like BOI to facilitate writing the data back to Sage 100 following a PUT/POST/DELETE request. If you are likely to get further reuse out of the Sdata provider you create, or if the RESTful nature of Sdata is a better fit for your consuming code, then it may still have value. But if not it might not be worth the extra time it would take to develop the Sdata provider.
