### ISSUE TITLE
Sage 50 - retrieving transaction

### ISSUE THREAD

**Issue by gustotelecom** [Sage/SData-2.0#80]
Hi there,

I am trying to pull all transactions linked to a trade account, but to no avail.

Please see attached snapshot of what I need to query.

I can't seem to find where this is stored, or how to get to it. I have tried searching in tradeAccounts but don't seem to get anywhere.

Any help would be gratefully received.

Stuart
<img width="866" alt="grab" src="https://cloud.githubusercontent.com/assets/22471314/24144794/80e48e80-0e26-11e7-8f85-b729d0fca2b9.png">

**Comment by darroncockram** [comment]
TradingAccounts are customers and suppliers in Sage 50 Accounts terminology so you won't see any transnational information on those resource kinds. The Sage 50 Accounts adapter does expose some, albeit very limited, transactional information via the custom feed tradingActivities.

**Comment by gustotelecom** [comment]
Hi Darron,

Thank you for getting back to me. Funnily enough I was just playing with tradingActivites, but as yet have not managed to get a response without it timing out, presumably because I am not asking it the right questions. With relation to my above post, do you know what parameters equal which fields with the screenshot I attached?

**Comment by darroncockram** [comment]
If the request is timing out the most likely thing you will be doing is asking for too much information in one hit e.g. not applying any paging and returning the whole feed in one go. Even with a medium sized dataset returning the whole feed could take a while. You will definitely want to apply paging (see this page for info http://sage.github.io/SData-2.0/pages/core/0604/) to limit the size of the returned data to manageable levels.

**Comment by gustotelecom** [comment]
Hi Darron,

Thank you so much, that did the trick!

My last question is around how I retrieve the transaction number listed in 1st column of my screenshot, in my case 121611? This is not returned in the atom feed as far as I can see, do I need to include a specific feed or perform an alternative lookup?

**Comment by darroncockram** [comment]
If the number in the screen shot is the 'header number' then it will be returned in the tradingActivities feed but if it is the 'split number' that would not be exposed to the Sdata feeds at all I'm afraid.

**Comment by gustotelecom** [comment]
Thank you for your reply, Darron.

Apologies, I am not really that knowledgable on Sage nor terminologies around it. The number shown is the ID that is attributed to that 'transaction'. This is used by our accounts team to marry sales orders to money taken (multiple to single). The header number that is returned, as far as I can see, is not viewable from within Sage 50. Equally, the number that is a 'key' within Sage is not accessible from the SData feeds?

Attached is a similar transaction to those already posted, but viewing the record in more detail.

For this, I am returned a header number of 94511, but as you can see the only number I can view against this activity is 121922. I have blanked out other fields for obvious reasons.

Can you confirm what I believe to be correct, is indeed correct? It seems rather odd not to return this key numeric when it is shown inside Sage, and likewise in the reverse with header number. Can the header number be viewed from within Sage 50?

![grab](https://cloud.githubusercontent.com/assets/22471314/24200091/da2c62f0-0f03-11e7-9ed8-18c591647ee9.png)

**Comment by darroncockram** [comment]
The Sdata adapter implemented by Sage 50 Accounts adheres to the GCRM contract so the schema is not specific to the product but rather is generic (deliberately so). This means that many concepts in the application do not map directly, or at all, to the Sdata feeds. I suspect that the number you are looking at is the split number rather than the header number and the split data is unfortunately not exposed to the Sdata feeds I'm afraid.

**Comment by gustotelecom** [comment]
Thank you once again Darron for getting back to me so quickly, it is really very much appreciated.

I understand, and that is, in this case, a shame. I don't suppose you have any suggestions where perhaps the header number is exposed within Sage? I just really need an identifier that is both visible within Sage and the Sdata feeds for both to correlate.

If it means further look-ups, or finding the transaction in a less direct way, I really don't mind!

**Comment by darroncockram** [comment]
It's been a while since I worked on Accounts but I can't recall where, if anywhere, the header number would be displayed. Having said that that trying to directly correlate data between the application specific view of the world and the GCRM contract view of the world is likely to end up as an exercise in frustration. They are quite different, and in your particular case the tradingActivities feed is only a small subset of the whole header/split/allocation data that is available in the application so it's likely you'll not find what you want in the feeds in this case as it's just not there.

What is it that you are trying to achieve by correlating the data? The tradingActivities feed is read only so generally speaking it's probably only useful for retrieving data for simple display or summary purposes.
