### ISSUE TITLE
Sage 50 Post SalesOrder Error

### ISSUE THREAD

**Issue by ChrisCrawshaw** [Sage/SData-2.0#81]
I've trying to create a Sales Order record by posting to http://sage-server:5493/sdata/accounts50/GCRM/-/salesOrders

SData is giving the following error:
POST operation failed - Object reference not set to an instance of an object.

   at Sage.Integration.Accounts50.SDOAdapter.Feeds.salesOrderFeedEntry.Add(IRequest request)
   at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.OnPostRequest(IRequest request)
   at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.PostRequest(IRequest request)
   at Sage.Integration.Accounts50.SDOAdapter.SDORequestManager.PostRequest(IRequest request) (-1)

Attached is an example of my xml. I've tried numerous variations on this. I can PUT to update values of an existing Sales Order but can't create.

[salesOrder.txt](https://github.com/Sage/SData-2.0/files/870655/salesOrder.txt)

**Comment by ChrisCrawshaw** [comment]
Found this issue was with the tradingAccount which is required and needs to be in the form:
`<tradingAccount sdata:url="http://localhost:5493/sdata/Accounts50/GCRM/-/tradingAccountCustomer(27f3f73b-62a8-4618-ae8b-04f7d930c414)?format=atomentry" sdata:uuid="27f3f73b-62a8-4618-ae8b-04f7d930c414" />`

**Comment by AlfredGreene** [comment]
Hi Chris, 
Can i ask how you are posting the data across. I can update current salesOrders but an having an issue creating a new order.
I wish Sage would give a bit more support to SData.
I am using PHP and posting data across via cURL but as said only issue is creating new sales order.
I am assuming i need to somehow generate a sales order ID in sage via a call and then use the returned id to post the new sales order.
Any help for a fellow coder would be most welcome. and i will owe you a beer :)

**Comment by darroncockram** [comment]
You should not need to to generate a new order number. The adapter should handle that for you.

If you have a look at #67 issue I have an example of a working payload for creating a new salesOrder which will hopefully help. Note that the example is when POSTing to the Sage 50 Accounts adapter so if you are using another application you may want to check it;s schema to make sure there are no additional required fields.

**Comment by ChrisCrawshaw** [comment]
I'm using C#.NET and sending a HTTPWebRequest to create.

As well as Darron's comment, I found you have to include the Sales Order Line Items in the create statement, you can't create them later attaching to the Sales Order nor update the Sales Order with them included.

**Comment by AlfredGreene** [comment]
Gents you both are owed a beer from me.
Been banging my head on that one a bit. have managed to create at last had the view update orders working but the creation was proving a real pain.
When i get the full php system working i will put the full thing up as a guide for others to build on.
Once again many thanks.

**Comment by jaythegeek** [comment]
@AlfredGreene You wouldn't happen to have an example of the code you used for creating SalesOrders would you? We are a little stuck here and the docs are sparse at best.

**Comment by AlfredGreene** [comment]
@jaythegeek I will drop you an email Jay. Docs are very sparse unfortunately.

**Comment by cal-tec** [comment]
@AlfredGreene Did you ever get this working as you needed. I have had similar issues regarding documentation on Sage 50 and SData. I am making progress and can create sales orders but I am having issues with adding lines to an existing sales order and also allocating stock. If you can share what you managed to work out it may be really helpful.

**Comment by darroncockram** [comment]
If you issue a $schema request you will see that the canPut attribute is false for the salesOrder resource kind. This means you cannot edit an existing sales order via the Sdata feeds I'm afraid.

**Comment by cal-tec** [comment]
@darroncockram I thought I was working to the $schema....

I was working on the assumption that the schema for salesOrderLine  says you canPost="true"

`<xs:element name="salesOrderLine" type="crm:salesOrderLine--type" sme:canGet="true" sme:canPost="true" sme:canPut="false" sme:canDelete="false" sme:canSearch="false" sme:pluralName="salesOrderLines" sme:canPagePrevious="false" sme:canPageNext="false" sme:canPageIndex="false" sme:supportsETag="false" sme:hasUuid="true" sme:batchingMode="none" sme:role="resourceKind" sme:isSyncSource="false" sme:isSyncTarget="false"/>`

Also I see that you are correct in saying that canPut="false" for the salesOrder endpoint but that is not actually true.

I can issue a  PUT request with the following and it is accepted and in this case updates the customerReference successfully

`<?xml version="1.0" encoding="utf-8"?>
<entry xmlns:atom="http://www.w3.org/2005/Atom" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cf="http://www.microsoft.com/schemas/rss/core/2005" xmlns="http://www.w3.org/2005/Atom" xmlns:http="http://schemas.sage.com/sdata/http/2008/1" xmlns:sdatasync="http://schemas.sage.com/sdata/sync/2008/1" xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmlns:sme="http://schemas.sage.com/sdata/sme/2007" xmlns:sdata="http://schemas.sage.com/sdata/2008/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <sdata:payload>
        <salesOrder xmlns="http://schemas.sage.com/crmErp/2008">
            <customerReference>Testing 1234</customerReference>
        </salesOrder>
    </sdata:payload>
</entry>`


Being totally honest I have very little faith in SData as the functionality is so limited for absolutely no reason. I understand that sage wants developers to pay for access to SDO but this does little to help people developing systems requiring true integrations, especially when dealing with cross-platform or web-connected environments. 

The documentation is not only lacking but as proved above fundamentally incorrect in places. 
In 2022 it should be possible to at the very least create, update, allocate stock and amend stock allocations programmatically via a well designed API.

 I have had endless trouble working with the SData accounts50 API so far and I had to compile your example code and then grab the network packets with Wireshark in order to understand why the xml I was submitting via an alternative language was not giving the expected result..... To be honest .... Im still not sure why but it shouldnt take reverse engineering like that to be able to interact with an API.

I understand that this is not your fault and I am eternally grateful that you uploaded your example repository but it has been a highly frustrating and time-consuming exercise only to find that SData is so limited that it likely will not do the job that I need it to. I have even spoken to some sage developer partners today that have concerns that SDO may not support the functionality needed either.

It is so frustrating that Sage as a business can not see the need for open access to data as they are obviously just pushing themselves out of the market compared to other systems.

I have seen that the Accounts50SDataInstaller has been moved to another repository and read your posts on the reasoning behind this, does this mean that we may see more functionality added to the accounts50 connector in the near future?

**Comment by darroncockram** [comment]
> Also I see that you are correct in saying that canPut="false" for the salesOrder endpoint but that is not actually true.
> I can issue a PUT request with the following to salesOrder({$UUID}) and it is accepted and in this case updates the customerReference successfully

Sad to say that is more through luck than design. If the adapter were responding the way it is supposed to you'd get a 400 error response when trying to PUT to a resource that does not support it. It sounds like that isn't happening and because it was let through that it is hitting a default handler. Unfortunately that means all bets are off in terms of success/reliability of the operation.

> Being totally honest I have very little faith in SData as the functionality is so limited for absolutely no reason. I understand that sage wants developers to pay for access to SDO but this does little to help people developing systems requiring true integrations, especially when dealing with cross-platform or web-connected environments.

> it has been a highly frustrating and time-consuming exercise only to find that SData is so limited that it likely will not do the job that I need it to.

Preaching to the choir there. I too have been quite disappointed that Sdata hasn't lived up to it's original intent/potential and hasn't had the investment to get it 'up to spec' as a true replacement for the product specific SDKs, which was the original concept. There were plans to have a lot more in terms of documentation, helps files, online support and code samples for Sdata. Unfortunately this hasn't come to pass so I just try to fill in some of the gaps when/where I can.

>I have even spoken to some sage developer partners today that have concerns that SDO may not support the functionality needed either.
SDO should provide access to almost everything in 50 Accounts and you can create some very tight and low level integrations using it. There are a few omissions that have crept in over the years (see my response on this post - https://www.sagecity.com/gb/sage-50-accounts-and-sage-50cloud-accounts-uk/f/sage-50-accounts-and-sage-50cloud-accounts-uk-general-discussion/182409/issue-using-the-sage-data-objects-to-update-report_password) but it's largely a case of a few fields here and there that aren't exposed. It's somewhat off topic for this forum but if there are any omissions to SDO that you think would block you from creating an integration please raise a request on the ideas board and I'll do my best to get them raised with the team.

>I have seen that the Accounts50SDataInstaller has been moved to another repository and read your posts on the reasoning behind this, does this mean that we may see more functionality added to the accounts50 connector in the near future?
I'm not aware of any specific updates planned in the immediate future but it is my hope that we will be seeing more changes, even if just to get some of the longstanding bugs resolved. Certainly the reasoning behind the change to distribution is to allow more frequent updates that are not tied to a release of Accounts. I'll be crossing my fingers as much as anyone hoping for more updates.
