### ISSUE TITLE
Sage 50 - Product Code Removing Special Characters on create of commodity

### ISSUE THREAD

**Issue by ChrisCrawshaw** [Sage/SData-2.0#85]
Hi, We've noticed that using SDATA, the product code is removing specials characters like hyphens and forward slashes. Is this by design? Is there any way to stop this from happening?
Thanks

**Comment by darroncockram** [comment]
You don't say which product or Sdata adapter you are referring to but I'll hazard a guess this is Sage 50 Accounts you are using. If so then the removal of special characters is intentional and you cannot override this behaviour I'm afraid.

**Comment by ChrisCrawshaw** [comment]
Thanks for the response Darron. Yes it's Sage 50 Accounts. This is interesting in that you can add them directly in to Sage with this characters. Are there any other gotchas like this, or is there a reference I can read through? 
Thanks

**Comment by darroncockram** [comment]
The only reference is the Sdata specification itself (http://sage.github.io/SData-2.0/pages/core/0100/). Individual providers are considered self-documenting via the instance schema, although detailed nuances such as the one you have encountered aren't really captured anywhere (except on this forum I suppose).

In terms of gotchas the thing that seems to trip people up the most when starting to work with Sdata is the contracts (the GCRM contract in the case of Sage 50 Accounts). Most people assume that the Sdata feeds are specific to a particular product and that there is a 1:1 mapping of every field/concept in the product to the Sdata feeds, but this is not the case. The Sdata contracts are, for the most part, deliberately generic and designed to cover a range of different products rather than and particular one(s).

What this means practically is that some concepts/features in a particular product are available via Sdata but use different terminology - a good example of this is that customers and suppliers in Sage 50 Accounts are surfaced as trading accounts in the Sdata feeds - whilst others may not be available at all or are surfaced but only in a very limited form.
